name: fsd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nvidia/label/cuda-12.8.1::cuda-toolkit
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.8.*
    - torchvision==0.23.*
    - transformers==4.56.*
    - diffusers==0.35.*
    - huggingface-hub==0.34.*
    - accelerate==1.10.*
    - sentencepiece==0.2.1
    - einops
    - wandb
    - bitsandbytes==0.47.0
    - ml-collections
    - gpytorch
    - deepspeed==0.17.*
    - peft==0.17.*
    # For Gemma:
    - timm
    # For OCR:
    - paddlepaddle-gpu==2.6.2
    - paddleocr==2.9.1
    - python-Levenshtein

# Pre-download OCR model:
# from paddleocr import PaddleOCR
# ocr = PaddleOCR(use_angle_cls=False, lang="en", use_gpu=False, show_log=False)